import { NextResponse } from "next/server";
import {
  getDefaultWorkspaceMembership,
  getSessionUser,
  getWorkspaceAccessForMutation,
} from "@/lib/auth/workspace";
import { createAdminClient } from "@/lib/supabase/admin";
import { apiRateLimiter, getClientIP } from "@/lib/rate-limit";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

/**
 * GET /api/cases
 * List cases newest-first. Optional ?limit=N.
 */
export async function GET(request: Request) {
  const { searchParams } = new URL(request.url);
  const limit = Math.min(parseInt(searchParams.get("limit") ?? "50", 10), 200);
  const workspaceSlug = searchParams.get("workspace");

  const user = await getSessionUser();
  if (!user) {
    return NextResponse.json({ error: "Authentication required" }, { status: 401 });
  }

  const access = workspaceSlug
    ? await getWorkspaceAccessForMutation(workspaceSlug)
    : await getDefaultWorkspaceMembership();

  if (!access) {
    return NextResponse.json({ error: "Workspace access required" }, { status: 403 });
  }

  const admin = createAdminClient();
  const { data, error } = await admin
    .from("cases")
    .select("*")
    .eq("workspace_id", access.workspace.id)
    .order("created_at", { ascending: false })
    .limit(limit);

  if (error) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
  return NextResponse.json({ cases: data ?? [] });
}

/**
 * POST /api/cases
 * Body: { title, body, customer_name?, customer_account?, customer_plan?, sample_id? }
 * Creates a new case (source: intake unless sample_id provided).
 */
export async function POST(request: Request) {
  const ip = getClientIP(request);
  const rl = apiRateLimiter.check(ip);
  if (!rl.success) {
    return NextResponse.json(
      { error: "Too many requests. Please try again later." },
      { status: 429, headers: { "Retry-After": String(Math.ceil((rl.resetAt - Date.now()) / 1000)) } },
    );
  }

  let body: Record<string, unknown>;
  try {
    body = await request.json();
  } catch {
    return NextResponse.json({ error: "Invalid JSON body" }, { status: 400 });
  }

  const title = typeof body.title === "string" ? body.title.trim() : "";
  const bodyText = typeof body.body === "string" ? body.body.trim() : "";
  const workspaceSlug = typeof body.workspace_slug === "string" ? body.workspace_slug.trim() : "";
  if (!title || title.length < 3) {
    return NextResponse.json(
      { error: "Field 'title' is required (min 3 chars)" },
      { status: 400 },
    );
  }
  if (!bodyText || bodyText.length < 10) {
    return NextResponse.json(
      { error: "Field 'body' is required (min 10 chars)" },
      { status: 400 },
    );
  }

  const user = await getSessionUser();
  if (!user) {
    return NextResponse.json({ error: "Authentication required" }, { status: 401 });
  }

  const access = await getWorkspaceAccessForMutation(workspaceSlug);
  if (!access) {
    return NextResponse.json({ error: "Workspace access required" }, { status: 403 });
  }

  const admin = createAdminClient();

  // case_ref is generated by Postgres sequence (see migration 002) —
  // atomic, no read-modify-write race.
  const payload = {
    workspace_id: access.workspace.id,
    title,
    body: bodyText,
    source: body.sample_id ? ("sample" as const) : ("intake" as const),
    sample_id: typeof body.sample_id === "string" ? body.sample_id : null,
    created_by: user.id,
    customer_name: typeof body.customer_name === "string" ? body.customer_name : null,
    customer_account:
      typeof body.customer_account === "string" ? body.customer_account : null,
    customer_plan:
      typeof body.customer_plan === "string" ? body.customer_plan : null,
  };

  const { data, error } = await admin
    .from("cases")
    .insert(payload)
    .select()
    .single();

  if (error) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
  return NextResponse.json({ case: data }, { status: 201 });
}
